chore: changes on return data body
paulovareiro29/gym-buddy-api pull request #51
Opened 2024-05-09 23:22 UTC by DiogoBernardes

2024-05-10 14:46 UTC, paulovareiro29 requested changes

2024-05-10 14:46 UTC, paulovareiro29 commented on src/controllers/exercise/index.ts
> +      if (body.machine_id !== undefined) {
porque isto?

2024-05-10 14:46 UTC, paulovareiro29 commented on src/controllers/metricTypes/index.ts
> +    return response.success({ data: { metricsTypes } });
```suggestion
    return response.success({ data: { metricTypes } });
```

2024-05-10 14:46 UTC, paulovareiro29 commented on src/controllers/metricTypes/index.ts
> +    return response.success({ data: { metricsType } });
```suggestion
    return response.success({ data: { metricTypes } });
```

2024-05-10 14:46 UTC, paulovareiro29 commented on src/controllers/metricTypes/index.ts
> +      return response.success({ data: { metricsType } });
```suggestion
      return response.success({ data: { metricType } });
```

2024-05-10 14:47 UTC, DiogoBernardes commented on src/controllers/exercise/index.ts
> +      if (body.machine_id !== undefined) {
Já foi alterado.

2024-05-10 20:12 UTC, paulovareiro29 commented on src/controllers/exercise/index.ts
> +      if (body.machine_id !== undefined) {
mas porque o !== undefined, sendo que if (body.machine_id) já verifica se é diferente de undefined

2024-05-10 20:12 UTC, paulovareiro29 commented on src/controllers/exercise/index.ts
> +      if (body.machine_id !== undefined) {
@DiogoBernardes

2024-05-11 14:19 UTC, DiogoBernardes commented on src/controllers/exercise/index.ts
> +      if (body.machine_id !== undefined) {
Porque como estavamos com o problema no patch eu alterei para testar só, e depois esqueci-me de retirar, entretanto já está direito no outro commit.

2024-05-11 14:58 UTC, paulovareiro29 approved these changes

2024-05-11 15:15 UTC, Oigres2 approved these changes

2024-05-11 15:28 UTC, merged